<?php
use ShavingShop\Models\Deliveries\DeliveryInterface;
use ShavingShop\Models\Product;
use ShavingShop\Models\SubscriptionForm;

/* @var SubscriptionForm $form */
/* @var Product[] $products */
/* @var DeliveryInterface[] $deliveries */
/* @var string $action */
?>
<html>
<head>
    <title>Сервис продажи бритвенных станков</title>
</head>
<body>
    <h1>Сервис продажи бритвенных станков</h1>

    <h2><?= $action; ?> подписки:</h2>
    <form method="post">
        <label for="product">Товар:</label>
        <select id="product" name="Subscription[product]">
            <?php foreach ($products as $product) : ?>
                <option value="<?= $product->name; ?>" <?= $form->product === $product->name ? ' selected' : ''; ?>><?= $product->name . ' - ' . $product->cost . '$'; ?></option>
            <?php endforeach; ?>
        </select>
        <br>
        <label for="type">Доставка:</label>
        <select id="type" name="Subscription[type]">
            <?php foreach ($deliveries as $delivery) : ?>
                <option value="<?= $delivery->getId(); ?>" <?= $form->deliveryType === $delivery->getId() ? ' selected' : ''; ?>>Один раз в месяц</option>
            <?php endforeach; ?>
        </select>
        <br>
        <label for="day">День:</label><input id="day" name="Subscription[day]" value="<?= $form->deliveryDay; ?>">
        <label for="secondDay">Второй день:</label><input id="secondDay" name="Subscription[secondDay]" value="<?= $form->deliverySecondDayOrMonth; ?>">
        <br>
        <input type="submit" value="Оформить подписку">
    </form>
    <br>
    <a href="/">Назад</a>
</body>
</html>