<?php
use ShavingShop\Models\Subscription;

/* @var Subscription $activeSubscription текущая подписка */

$cost = $activeSubscription->getProduct()->cost;
$product = $activeSubscription->getProduct()->name;
$totalCost = 0;
?>
<html>
<head>
    <title>Сервис продажи бритвенных станков</title>
</head>
<body>
    <h1>Сервис продажи бритвенных станков</h1>

    <?php if ($activeSubscription) : ?>
    <h2>Предыдущие поставки "<?= $product; ?>"</h2>
        <p>
            <?php $dates = $activeSubscription->getDelivery()->getDeliveryDates(
                $activeSubscription->getStartDate()
            ); ?>
            <?php foreach ($dates as $date) : ?>
                <?= $date->format('d.m.Y'); ?> - <?= $cost; ?>$<br>
                <?php $totalCost += $cost; ?>
            <?php endforeach; ?>
            Итого потрачено: <?= $totalCost ?>$
        </p>
    <?php endif; ?>
    <a href="/">Активная подписка</a>
</body>
</html>