<?php
use ShavingShop\Models\Subscription;

/* @var Subscription[] $subscriptions текущая подписка */

?>
<html>
<head>
    <title>Сервис продажи бритвенных станков</title>
</head>
<body>
    <h1>Сервис продажи бритвенных станков</h1>

    <?php foreach ($subscriptions as $subscription) : ?>
    <?php
    $cost = $subscription->getProduct()->cost;
    $product = $subscription->getProduct()->name;
    $totalCost = 0;
    ?>
    <h2>Предыдущие поставки "<?= $product; ?>"</h2>
        <p>
            <?php $dates = $subscription->getDelivery()->getDeliveryDates(
                $subscription->getPeriod()->getStartDate(),
                $subscription->getPeriod()->getEndDate()
            ); ?>
            <?php foreach ($dates as $date) : ?>
                <?= $date->format('d.m.Y'); ?> - <?= $cost; ?>$<br>
                <?php $totalCost += $cost; ?>
            <?php endforeach; ?>
            Итого потрачено: <?= $totalCost ?>$
        </p>
    <?php endforeach; ?>
    <a href="/">Активная подписка</a>
</body>
</html>