<?php
use ShavingShop\Models\Subscription;

/* @var Subscription $activeSubscription текущая подписка */
?>
<html>
<head>
    <title>Сервис продажи бритвенных станков</title>
</head>
<body>
    <h1>Сервис продажи бритвенных станков</h1>

    <?php if ($activeSubscription) : ?>
    <h2>Текущая подписка:</h2>
        <p>
            <?php $product = $activeSubscription->getProduct(); ?>
            <?= $product->name; ?> за <?= $product->cost; ?>$
            <?= $activeSubscription->getDelivery()->getDescription(); ?>
            начиная с <?= $activeSubscription->getPeriod()->getStartDate()->format('d.m.Y'); ?>

            <br>
            <a href="/clear/<?= $activeSubscription->getId(); ?>">Отменить подписку</a>
        </p>
    <?php else : ?>
        <p>
            У вас нет активных подписок<br>
            <a href="/create">Создать</a>
        </p>
    <?php endif; ?>
    <a href="/history">Предыдущие поставки</a>
<hr>
<a href="/restore">Откатить все изменения над подписками</a>
</body>
</html>